export const CLEAR_VSF_MONTHLY_STATS = 'CLEAR_VSF_MONTHLY_STATS';
export const CLEAR_VSF_SUMMARY_STATS = 'CLEAR_VSF_SUMMARY_STATS';
export const UPDATE_VSF_MONTHLY_STATS_DATE = 'UPDATE_VSF_MONTHLY_STATS_DATE';
export const UPDATE_VSF_SUMMARY_STATS_TIME_FRAME = 'UPDATE_VSF_SUMMARY_STATS_TIME_FRAME';
export const FETCH_VSF_MONTHLY_STATS = 'FETCH_VSF_MONTHLY_STATS';
export const FETCH_VSF_SUMMARY_STATS = 'FETCH_VSF_SUMMARY_STATS';
