export const CLEAR_SMS_MONTHLY_STATS = 'CLEAR_SMS_MONTHLY_STATS';
export const CLEAR_SMS_SUMMARY_STATS = 'CLEAR_SMS_SUMMARY_STATS';
export const UPDATE_SMS_MONTHLY_STATS_DATE = 'UPDATE_SMS_MONTHLY_STATS_DATE';
export const UPDATE_SMS_SUMMARY_STATS_TIME_FRAME = 'UPDATE_SMS_SUMMARY_STATS_TIME_FRAME';
export const FETCH_SMS_MONTHLY_STATS = 'FETCH_SMS_MONTHLY_STATS';
export const FETCH_SMS_SUMMARY_STATS = 'FETCH_SMS_SUMMARY_STATS';
