import { isString } from 'lodash';

/**
 * @method getRedirectPath
 * to get the redirect path from the result generated by react-router
 *
 * @param redirectLocation {Object} the result object returned by react-router
 * @param redirectLocation.pathname {String}
 * @param redirectLocation.search {String}
 * @throws Will throw an error if the argument does not contain key `pathname`
 *
 * @returns {String} redirect path
 * @see {@link https://github.com/reactjs/react-router/blob/master/docs%2Fguides%2FServerRendering.md}
 */
export function getRedirectPath(redirectLocation) {
  const { pathname, search } = redirectLocation;

  if (!pathname) {
    throw new Error('object key `pathname` is missing from the argument.');
  }

  if (!isString(pathname) || !isString(search)) {
    throw new Error('object key `pathname` or `search` from argument must be a string.');
  }

  return `${pathname}${search}`;
}
