export const CLEAR_OVERVIEW_SUMMARY_STATS = 'CLEAR_OVERVIEW_SUMMARY_STATS';
export const CLEAR_OVERVIEW_DETAIL_STATS = 'CLEAR_OVERVIEW_DETAIL_STATS';
export const FETCH_OVERVIEW_SUMMARY_STATS = 'FETCH_OVERVIEW_SUMMARY_STATS';
export const FETCH_OVERVIEW_DETAIL_STATS = 'FETCH_OVERVIEW_DETAIL_STATS';
export const UPDATE_OVERVIEW_DETAIL_STATS_TIME_FRAME = 'UPDATE_OVERVIEW_DETAIL_STATS_TIME_FRAME';
