export default {
  OVERVIEW: 'overview',
  ACCOUNT: 'account',
  COMPANY: 'company',
  END_USER: 'end-user',
  CALL: 'call',
  IM: 'im',
  SMS: 'sms',
  VSF: 'vsf',
  TOP_UP: 'top-up',
  VERIFICATION_SDK: 'verification-sdk',
  ACCESS_MANAGEMENT: 'access-management',
  ACTIVE: 'Active',
  INPROGRESS: 'In Progress',
  SUSPENDED: 'Suspended',
  NONE: 'None',
};
